[workspace]
resolver = "2"
members = [
    "common",
    "control",
    "functions",
    "guessing_game",
    "hello_cargo",
    "hello_world",
    "ownership",
    "structs",
]
default-members = ["structs"]
