[workspace]
resolver = "2"
members = [
    "c1_hello_world",
    "c2_guessing_game",
    "c3_common",
    "c4_ownership",
    "c5_structs",
    "c6_enums",
    "c7_module_system",
    "c8_collections",
]
default-members = ["c8_collections"]
